### ISSUE TITLE
Aviation Engine Types and Node Placement

### ISSUE THREAD

**Issue by Jesse931** [KSP-RO/RP-0#1417] opened 2020-12-14 01:58 UTC
So, I'll start this off by acknowledging that most people either don't care for the airplanes, or actively avoid them.

That being said, there's some very confusing stuff going on in the aviation tree.

We start off with the Rolls-Royce Derwent V, an engine which dates back to the Gloster Meteor. In itself, this is...fine. But seeing as the campaign starts off in 1951, we really should have the Nene instead. It's roughly 80% more powerful. More relevantly, it still has the bulky centrifugal flow compressor (where'd the model for that go, anyway?) so it won't let you make efficient supersonic jets with the start node.

Then, in the Supersonic Flight node (incidentally symbolized by a MiG-19 and denoted as being the 1950-51 period), we get a P&W J85 GE-4. There was indeed a variant of the J85 that was used on a supersonic aircraft, but it wasn't the GE-4. It was the GE-21 on the F-5 Tiger, which had an afterburner and around 3 kN more dry thrust. The GE-4 mainly saw use on the T-2 Buckeye trainer aircraft, a decidedly subsonic design. The time is appropriate; the node is not. The "supersonic" version of the J85 wouldn't be put in a plane until 1959.

Next, in Mature Supersonic Flight (symbolized by the Starfighter, representing tech from 1952-1955), we get the J57, an engine that was actually used on an aircraft that was supersonic, and which was first run in 1950. By the supposed 'time' of the node, the  J57 had already been mounted in a F-100 (which first flew in 1953). This is still more or less appropriate, but I would expect that a cutting-edge aerospace firm like a space agency would be among the first to get access to a modern jet like this.

Perplexingly, the XF-104 Starfighter first flew in 1954 (a time period that is in this node). Its engine, the J75, will not be accessible to the player until the 1964 node, which falls 5 years before the F-104's last version would be retired from American service. Similarly, the first prototype English Electric Lightning (the P.1A) also first flew in 1954, though the first Mach 2-capable version wouldn't fly until 1957. Just as oddly, the intake piece for the F-104 is in the 1952-55 node, but the engine that goes with that intake isn't.

The P&W J75, the engine which powered the Delta Dart/Dagger, also comes about 3 years too late. The F-106 first flew in 1956, but we don't get its engine until the 1959 node, which lines up to when the aircraft was adopted after a difficult development process.

Lastly, the Continental IO-550B is from the 1980s, and is a starting tech.

Now that I have established the weird stuff that's going on here, I'm going to present a (hopefully fairly simple) solution to the problem.

I'm not sure what can be done about the Derwent engine. Thus, I'll leave that one alone in the below plan:

The J85 is awkward, being an engine that was first run in 1954 - but would be obsolete in the 1954 tech node, especially seeing as all of the AJE compressor sections appear to have vanished (or maybe that's just me?). Placing it in the first aviation node to make space for other engines makes sense from a gameplay perspective.

The J57 can be moved down one tech node in my opinion, to 1950-51. It won't be researched until 1952 anyway, and that's two years after the first variant of the engine first ran.

The J79 absolutely belongs in the 1952-55 tech node, as all of the other parts related to the F-104 are already in that node.

The J75 can stay in the 1959 tech node. It has more thrust than the J79 which currently comes after it, so it's a sensible path upward in terms of engine power.

The Rolls-Royce Avon is another tough one. Its performance is pretty much on par with the J79, but the engine does come from at least 7 years later. Moving it to the 1959 tech node would be a reasonable compromise, I think. That way, it offers slightly less thrust than the J79 which came before it, but is far cheaper (thus quicker to build, if my understanding of KCT is correct).

Thus, my suggestion for new node placements below:

Supersonic Plane Development (post-war)
-P&W J85

Supersonic Flight (1950-51)
-P&W J57

Mature Supersonic Flight (1952-55)
-P&W J79

High Speed Flight (1959)
-P&W J75
-RR Avon

Look forward to seeing what others think.

**Comment by marsh1832** [comment] 2020-12-15 03:01
I’m one of those players that does care for airplanes and builds quite a few in my play throughs. I’m brainstorming an airplane contract pack/rework for rp1. Considering how devisive planes are im thinking I will separate the airplane contracts in the configuration entirely so that people can run airplane free careers and judge each other’s milestones based on airplane or no airplane contract setting, similar to how game speed runners use multiple categories based on how they do their runs.

Personally I think the superjunkers are already a “problem” and I wouldn’t want to make it even easier by buffing the derwent. If it were up to me I would gate the supersonic contract behind the first aviation and rocketry nodes.

I think the tree was designed in the way it was for gameplay reasons... post war tech was stretched out a bit compared to real history to allow for a smoother progression. But with the aviation engines, it seems less necessary.

I agree that the j85 comes a bit late. It’s a huge improvement over the derwent. I admit it’s a bit weird when building or upgrading craft that the in game j85 actually has less thrust than the derwent which means I usually have to nerf an existing design to make it fly with a j85 even though it’s the superior engine. The j85 should probably be it’s stronger after burning version, because the jump to the j57 is just obscene compared to derwent/j85 designs.

I’ve never even made it to the j79 lol

From a gameplay perspective shifting the tech one node forward makes a lot of sense. When you unlock the supersonic contracts which were designed for the j57, you don’t even have it unlocked yet, and tend to complete those contracts either with a rocket plate, or by contract scumming until you get something a superjunkers can barely complete.

Building a j57 plane is completely optional. I choose to because it’s easier than air launching a rocket plane. Moving it forward a node would make it more viable.

I agree with your logic about the aviation nodes, but I can’t comment on any specific reason they were set up that way.

**Comment by siimav** [comment] 2021-01-27 17:07
The thing to keep in mind is that not all engines ingame use their earliest RL configuration so looking at the date the engine was first flown isn't quite correct. #1424 should at least address the issue of having some worthwhile upgrades in the first aviation node.

**Comment by NathanKell** [comment] 2021-01-27 20:00
Derwent V *is* a Nene, a scaled down one. Like Delta IV they lifted the
name up and put a new engine underneath.

Compressors were from VSR I believe.

If memory serves engine choice was also limited by what we had good data
for, though I don't specifically recall the logic on node choice for later
jets.

Sent by my thumbs, slowly.

**Comment by Capkirk123** [comment] 2021-06-05 05:02
Just to add on, the clock in the top left might say 1951, but you start with 1945 tech (aerobee, A-4, etc). You need to research the Post-War nodes to get 1946 tech like the XLR11

**Comment by siimav** [comment] 2021-11-11 12:26
I think "Supersonic Plane Development (post-war)" node is now fine with the J47 in it. I agree that "Supersonic Flight (1950-51)" needs something better than J85 in it but J57 appears to be a too significant boost in engine performance. At least the config we have ingame right now.

**Comment by siimav** [comment] 2022-12-04 19:18
Kirk made a ton of changes to engines so hopefully there's a better progression now.

**Closed by siimav** 2022-12-04 19:18 UTC
