### ISSUE TITLE
SSTU tooling doesn't understand 0.25x length

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#938] opened 2018-12-11 20:28 UTC
(discussed on discord, but creating issue so it doesn't get lost)

https://github.com/KSP-RO/RP-0/blob/44ad20864f83f8263092d7ce20f8510d8bc47784/Source/Tooling/ModuleToolingSSTUTank.cs#L54

The Body Length multiplier 0.25x (the lowest one) was missed; ends up being treated as length=0

Presumably a trivial fix, but I don't have the dev environment to test it.

**Comment by pap1723** [comment] 2018-12-12 00:37
I guess I could catch it in the else statement. The issue is that there is no model for the 0.25 one and that is what we are reading. It must reuse a different model. Let me test to see if that works.

**Comment by lpgagnon** [comment] 2018-12-14 20:45
As discussed on discord: the 0.75x length is also not recognized, so "0.25x is nothing matches" turns out not to be an option.
Further experimentation shows 2 interesting facts:
- .25x and .75x don't have the V.Scale stretch slider; they only support one fixed length
- 0.5x does have a stretch slider, and it goes all the way from 0.5 to 1.5, so it actually covers the 0.25 (.5*.5) and 0.75 (.5*1.5) lengths.

This means the .25 and .75 multipliers are redundant. So if there's a simple way to just prevent them from being selectable in the UI, it'd sweep the problem under the carpet

**Comment by pap1723** [comment] 2018-12-17 16:35
Fixed with https://github.com/KSP-RO/RP-0/commit/8f007d0a546d985e86a7efe13686f411d1f1070e

**Closed by pap1723** 2018-12-17 16:35 UTC
