### ISSUE TITLE
Todo: Restrict Atlas/R-7 avionics, re-place parts

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#384] opened 2015-11-22 05:35 UTC
@ctiberious  @batuhantasli @Niemand303  et al.

Before we had to place tanks (with avionics in them) in the avionics node. I just added support for restricting avionics based on a tech node ( e43b0952ce1f48bdf298be9f69e4dd95823c5bfb ) and so the parts can be placed back in the construction node appropriate to them, but have their avionics restricted until basic avionics unlocks.

**Comment by batuhantasli** [comment] 2015-11-22 07:33
#387 can be merged

**Comment by ctiberious** [comment] 2016-01-08 17:22
In #417 and the various PRs that came of that discussion, I'm adjusting the placement of a number of Atlas and Titan tanks.  With the exception of the first Atlas tank which has a separate tech requirement for it's avionics package, all the Atlas and Titan tanks get their avionics updates at the same time that the tank becomes available.  Should I go through and add tech node requirements for the avionics portion of these tanks?

**Comment by ctiberious** [comment] 2016-01-08 18:15
I'm guessing there isn't a way to have one part with two different levels of avionics, each with a different tech requirement?  As an example, the Titan III and Titan IV both use the same 2nd stage fuel tank and we currently have the avionics for the Titan in it's 2nd stage.  The Titan III, however, needs less avionics than the Titan IV.  Is there a way to setup two avionics tech requirements for this one part so that the tank and Titan III avionics becomes available at one TL, but the Titan IV upgraded avionics (on the same part) isn't available until a later TL?

**Comment by NathanKell** [comment] 2016-01-08 18:40
There isn't right now. But Titan III should support Titan IV-level masses since Titan IIIM was broadly that mass anyway. Besides, past 1970 or so avionics move more and more digital and thus have far more headroom (c.f. the Saturn IU, which supports far more mass than the basic Saturn V--and is used on the Saturn IB as well!)

**Comment by NathanKell** [comment] 2016-01-08 18:41
As to your prior question, yes you should, because construction nodes should not unlock avionics, they should be unlocked in a corresponding avionics node IMO.

**Comment by ctiberious** [comment] 2016-01-11 17:54
It should be all part of #422 now.

**Comment by Schnobs** [comment] 2016-04-16 19:48
I just now unlocked some improved Atlas tanks and was frustrated to find out that they will not work until I unlock Flight Control.

I can see the point of incapacitating the Atlas until Basic Avionics has been researched: that node is a major breakthrough, unlocking the standard 2m and 3m avionics. One cannot piece together a LV of Atlas or R-7 like capabilities without that tech.

However, once that node has been researched, anything goes -- at least with proc parts. I don't quite see why prefab tanks need to be more limited than that.

**Comment by stratochief66** [comment] 2016-04-16 20:15
@schnobs ; I see us getting an equal amount of confusion and complaints if
prefab, historically representative tanks are placed before their place in
the timeline. can't please everybody at once.

also, as I said in the IRC, we will eventually have the option to embed a
more power efficient avionics ability into the later era tanks, so that
looks to me to be a minor reason to keep them historically placed.

**Comment by Schnobs** [comment] 2016-04-16 23:01
Well, the *tanks* are historically placed. They even unlock and are usable as tanks, only that you need to stick on an avionics module because the integrated avionics don't work.

I don't buy into the timeline argument. The tech tree gives the player a lot of freedom to do things their own way. If someone rushes a particular tech, then complains that it's available too early ... well, I don't know what to say.

If it's important that the player can not use a tank outside of its historical context, move them to the same node as their supposed payload. Atlas-Centaur tank to early hydrolox and so on.

But if it's a gameplay balance thing, that one should not enjoy the benefit of integrated avionics without having researched avionics in the first place, then the tanks should depend whatever node provides standalone avionics of the given weight. That would be Basic Avionics for all Atlas/Titan/R-7 type tanks.

**Comment by ctiberious** [comment] 2016-04-18 15:43
The problem is that we can't currently have one part with multiple avionics packages.  In a perfect world, I'd think we'd want most avionics parts (including prefab tanks) to have the massLimit for whatever avionics tech node the player had researched.  That way you always launch with basically the best massLimit regardless of what prefab tank you used.  But since we can't do that, I just put the avionics requirement into the same tech level as the prefab tank.
The only work around I can think of with the current code would be to remove the avionics from the prefab tanks completely.  But then you have to create something like 18 extra avionics parts just to cover Atlas, Titan and Centaur.

**Comment by Bornholio** [comment] 2018-12-10 00:40
Think this is all worked out, anyway you can do proc to fill in the gaps if needed. 
CLOSE ME?

**Closed** 2018-12-15 07:51 UTC
