### ISSUE TITLE
Contracts do not appear when using TextureReplacer

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#24] opened 2014-11-22 12:39 UTC
Steps to reproduce:
- Start a new game
- Go to mission control
- Observe the lack of contracts
- Time warp forward two weeks
- Still no contracts
- Sucks to be a space agency. :)

**Comment by pjf** [comment] 2015-03-05 02:40
This no longer appears to be an issue with newer versions of TextureReplacer! Closing issue.

**Comment by jwvanderbeck** [comment] 2015-03-05 02:53
Sorry but this is still a problem with TR unless there has been a version
released within the last days specifically to address it?

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NathanKell** [comment] 2015-03-05 02:57
@pjf: the issue appears to be that TR can call a Unity call that fails during texture load, which corrupts configs in GameDatabase, thus screwing everything up. It's very much still a problem, I gather with your changed modset you are no longer affected?

**Comment by pjf** [comment] 2015-03-05 03:02
Ah, dang. As the only other person on this ticket I was hoping this was a stale "just me" issue.

And yes, at least with my modset I'm not seeing any problems. Here's what that currently looks like:

```
KSP Version: 0.90.0

Installed Modules:

- ActiveTextureManagement-x64-Basic 4-3
- AdvancedJetEngine 2.0.3
- AGExt 1.30c
- AlternateResourcePanel 2.6.3.0
- BetterBuoyancy v1.1
- Chatterer 0.8.1
- CIT-Util 1.1.2
- CommunityResourcePack 0.3.3
- CommunityTechTree 1.1
- CrossFeedEnabler v3.2
- CustomBiomes v1.7.2
- CustomBiomes-Data-RSS v8.5
- DDSLoader 1.8.0.0
- DeadlyReentry v6.4.0
- DMagicOrbitalScience 0.9.2
- DogeCoinFlag v1.02
- EngineIgnitor-Unofficial-Repack 3.4.1.1-1
- EnhancedNavBall 1.3.5
? EVE-Overhaul-Core 0.0.2014.12.18
- FASA 5.215
- FerramAerospaceResearch v0.14.6
- FilterExtensions 1.17
- FinalFrontier 0.6.5-697
- FirespitterCore 7.0.5463.30802
- InfernalRobotics 0.19.3
- Karbonite 0.5.5
- KerbalAlarmClock v3.2.3.0
- KerbalConstructionTime 1.1.2
- KerbalJointReinforcement v3.1.1
- kOS 0.16.0
- KronalVesselViewer 0.0.4_0.90.0
- MechJeb2 2.4.2
- ModuleManager 2.5.9
- ModuleRCSFX v3.5
- PlanetShine 0.2.2.1
- PlanetShine-Config-Default 0.2.2.1
- PreciseNode 1.1.2
- ProceduralDynamics v0.9.3
- ProceduralFairings v3.11
- ProceduralParts v1.0.2
- RealChute 1.2.6.3
- RealFuels rf-v8.4
- RealismOverhaul v8.1.1
- RealPlume v8.1.1
- RealSolarSystem v8.5
- Regolith 0.1.7
- RemoteTech v1.6.3
^ RemoteTech-Config-RSS 0.0
- ResourceOverview 1.2.0.0
- RP-0 v0.24
- RSSTexturesDDS8192 1.0
? RVE-KSP-Haxx 0.0.2015.02.26
- SCANsat v10.0
- ScienceAlert 1.8.4
- Service-Compartments-6S 1.3
- ShipManifest 0.90.0_4.1.2
- SmokeScreen 2.5.3
- SXT 20
- TACLS v0.10.2b
- TACLS-Config-RealismOverhaul v8.1.1
- TechManager 1.5-compat
- TextureReplacer 2.2.5
- Toolbar 1.7.8
- TweakScale v1.50
- UKS 0.22.8
- UniversalStorage 1.0.90.2
- UniversalStorage-KAS Deprecated
- UniversalStorage-TAC Deprecated
- USITools 0.3.2
* VenStockRevamp v1.7.2
```

I believe the hypothesis was that TR was compressing flags. I'm guessing it's either stopped doing this, or more mods are coming with TR configs to protect their flags from compression.

**Comment by NathanKell** [comment] 2015-03-05 03:04
It may be that an early version was, which might have been an issue, but AFAICT the current version is not. Oh! I think I may know. Agathorn, you're on Doze, right? The GameDatabase issue is a failed D3D call as I recall, but perhaps the Linux issue *was* the flags? But there's enough other linux folks who were experiencing the issue (posted on forum) that I don't think we can yet say with certainty the linux side is fixed.

**Comment by jwvanderbeck** [comment] 2015-03-05 03:05
All I know is what Sarbian said, which is pretty much what you said :)
 Thing is though that it could be anything that TR corrupts on.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by 6forty** [comment] 2015-03-07 17:58
Disabling TR's texture unloading fixes the contract issues for me.

**Comment by jwvanderbeck** [comment] 2015-03-07 18:04
I don't know what that unloading feature is, but the root of the problem is
that TR is sometimes failing to load textures and instead of handling the
error, it is instead corrupting the game database.  Unfortunately despite
sarbian posting in the TR thread with all the details, i've yet to see Shaw
even acknowledge the issue.  Don't know if he missed the post or what.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by 6forty** [comment] 2015-03-07 19:12
I haven't seen sarbian's posts but I have seen a few others mention contracts being broken by TR, and that Shaw can't reproduce it. It doesn't seem to be TR itself, but TR + SXT.

With TR's default config and SXT installed I get the "Texture 'SXT/Agencies/KDB' is not readable" exception. That seems to completely break the fragile contracts system, since I also get a number of exceptions from ContractConfigurator failing to add SCANSat contracts and I get all those space center scene switching issues that happen when contracts in a savegame are broke.

Adding "^SXT/Agencies/" to TR's keepLoaded list or setting isUnloadingEnabled to never fixes all of the above for me. I've been able to reliably reproduce the issue and my solution on linux. Don't know how relevant that is, but mentioning it since @NathanKell did above.

**Comment by jwvanderbeck** [comment] 2015-03-07 19:43
Here is sarbian's post:
http://forum.kerbalspaceprogram.com/threads/107471-0-90-TextureReplacer-2-2-5-%2830-1-2015%29?p=1756570&viewfull=1#post1756570

It has nothing to do with any specific mod, it has to do with TR failing to
handle the D3D error.  Yes you can get around the error by manually
excluding mods, so that the errors don't happen in the first place,

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NathanKell** [comment] 2015-03-07 19:44
@jwvanderbeck as I said above there are two issues. As @6forty points out the most RP-0-relevant one has been found and there's a fix, but the one you are talking about (which is *not that one*) remains.

**Comment by jwvanderbeck** [comment] 2015-03-07 19:47
Well my point is that I think **all** of them can be "fixed" with proper
exclusions.  But end users don't know this, nor do it.  Which is why it
really needs to be handled properly by TR.  No matter how we look at it
though there isn't much we can do.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by Bornholio** [comment] 2018-12-09 22:45
Close this? Fixed long ago

**Closed** 2018-12-09 23:01 UTC
Labels: bug
