### ISSUE TITLE
demoting TestFlight to a "suggested" mod?

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RP-0#311] opened 2015-11-07 16:52 UTC
As per my rant on IRC just now: while I understand the importance of tests, I don't see the wisdom of having to do them myself. Design test article, construction, rollout, and waiting for the test to complete doesn't make for exciting gameplay.

It doesn't even scale: putting eight similar engines on the same test article will not increase the amount of data collected (or only if you run them sequentially).

There is a R&D button, "here you can allocate R&D teams to working on improving your hardware", but it's non-functional.

In my opinion, TestFlight in it's current state should not be part of the default RP-0 experience.

**Comment by batuhantasli** [comment] 2015-11-09 21:53
I have to agree with Schnobs. In addition to those issues, many engines missing TestFlight configs so IMO it does not make sense to put TestFlight in recommended mods list for now.

**Comment by NathanKell** [comment] 2015-11-12 08:07
tbh I kinda thought I had, but maybe I reverted it when it was confirmed working for 1.0.x.
@Schnobs if it doesn't scale from multiple engines that's a regression; it used to.

I concur with the demotion until such time as we have better configs.

**Comment by jwvanderbeck** [comment] 2015-11-12 15:33
It was my sincere hope that when I vanished, others would take up adding
configs.  Bit sad that didn't happen :(

I agree that it should be demoted if it doesn't work properly.  I wish I
could say I might come back and make it better, but sadly I don't have the
time nor honestly the inclination these days.  I have drifted away from KSP
in favor of working on my own game.

I am fully willing to accept PRs though that add additional configs or bug
fixes.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by stratochief66** [comment] 2015-11-12 17:00
@jwvanderbeck 

xShadowx has been working on more failure conditions for non-engine parts recently, so your mod is definitely well liked :)

In my opinion, to be broadly usable, TestFlight would need to be changed a bit to accept a Template structure, similar to what @Felger did with RealPlume. That would make it far, far easier to add TestFlight compatibility for new parts, or to update old ones. Further adding amplitude and burn time scaling to a template would allow easy coverage of all engines with basic compatibility (amplitude allowing you to scale an engine from a template to be twice or half as likely to fail every tick as the template, burnscale allowing a template to be stretched or squeezed from the template fail curve for a longer or shorter burn time rating)

I added one or two configs for TestFlight in the spring, and unfortunately I found it fairly difficult.

I understand that adding template support would probably require a bit of code change to the base mod, and I totally understand if you're not able to do that @jwvanderbeck, I'm just providing the idea.

Even a short tutorial might help, such as that provided for RealPlume:
https://github.com/KSP-RO/RealPlume/wiki
https://github.com/KSP-RO/RealPlume/wiki/Adding-a-Plume-to-an-Engine

With a basic tutorial provided, xShadowx (or others) might be able/willing to start adding engine compatibility for TestFlight.

**Comment by jwvanderbeck** [comment] 2015-11-13 02:37
Not sure what you mean by Templates?  Looks like RealPlume configs are just standard MM configs.  I chose to use my own file format because it actually means less work - you can reuse sections from existing configs.  But it still compiles down to MM config, and you could distribute standard MM configs as a side project if you desired.

As for tutorial, yeah my docs are a bit weak but there is this: https://github.com/jwvanderbeck/TestFlight/wiki/YAML-Configuration-Syntax

**Comment by NathanKell** [comment] 2015-11-13 03:44
I think what @stratochief66 might mean is to have reference links instead of copy-pasting, for configs. I.e. we could set any early kerolox booster to "early kerolox booster" type and the rest of the config would be generated from a master.

@jwvanderbeck I had intended to write the extra configs myself--Probus will vouch for this, we discussed it a couple months ago. But sadly that was right when 1.0.5 went from "NK is busy" to "NK? Who's NK?" so I didn't get to it.

I have a proposal then. If you're moving on (something I completely understand, and something I wish you the best of luck on) would you be interested in transferring the repo over to KSP-RO? That should make collaborational continuing of it rather easier.

**Comment by jwvanderbeck** [comment] 2015-11-13 03:48
> I.e. we could set any early kerolox booster to "early kerolox booster" type

Just make one full config for "Early Kerolox Booster" then apply it to all the engines.  That is what the YAML config lets you do :)

I have no idea how to transfer a repo but let me look into it.  I think it would break all my build systems though.

**Comment by NathanKell** [comment] 2015-11-13 03:51
Ah, ok, then great, what is asked for exists already, the best response :D

Hmm. Right, you have your own build server/system set up, forgot that bit. Though one presumes you would be left with joint ownership of the KSP-RO/TestFlight repo so your hooks would probably still be ok? Depends.

**Comment by jwvanderbeck** [comment] 2015-11-13 03:55
Probably just need to repoint everything.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by jwvanderbeck** [comment] 2015-11-13 04:04
I need admin rights in KSP-RO

**Comment by NathanKell** [comment] 2015-11-13 04:13
That's odd. Doesn't the settings->advanced panel of your repo have the option to 'transfer repo' ?

**Comment by jwvanderbeck** [comment] 2015-11-13 04:14
> Transfer this repository to another user or to an organization **where you have admin rights.**

And if I try to transfer it, it points out that I do not have admin rights :)

**Comment by NathanKell** [comment] 2015-11-13 04:15
Try again. Pls don't be evil kthx

**Comment by jwvanderbeck** [comment] 2015-11-13 04:17
Well considering you are admin of a repo that I pay for and has all my credit card information on it, I think we're even now :D

**Comment by NathanKell** [comment] 2015-11-13 04:20
Haha, right. :)

**Comment by stratochief66** [comment] 2016-07-08 15:48
TestFlight is back, baby!

Someone learning RP-0 and having a great deal of trouble could potentially play w/o TestFlight, but beyond that I think it is still highly recommended for all players.

We can probably close this Issue?

**Closed** 2016-07-08 16:20 UTC
