### ISSUE TITLE
Significant FPS drop with RP-0

### ISSUE THREAD

**Issue by Shurikeeen** [KSP-RO/RP-0#166] opened 2015-07-21 17:38 UTC
The contracts are causing a huge FPS drop. With RP-0 and ContractConfigurator I get 15 FPS on the pad with 1 part but when I remove them I get 90+ FPS.

**Comment by jrossignol** [comment] 2015-07-21 19:12
Are any contracts active?  I assume this is with the latest RP-0 pulled from git?  Does the frame rate jump back up after a little bit, or is it consistently lowered?  Any errors in the log?

**Comment by NathanKell** [comment] 2015-07-21 19:32
I have not encountered this issue myself. Shurikeen, can you try with only the required mods for RP-0 ?

**Comment by Shurikeeen** [comment] 2015-07-21 20:53
I have the auto-accepted contracts, a sounding and the unmanned karman line contracts active. After I complete the auto-accepted contracts the FPS jumps back up.

**Comment by jrossignol** [comment] 2015-07-21 21:02
I assume you have all four series of auto-accept contracts?  I took a look through, and nothing jumped out as being particularly bad.  I'll download them tonight and test it out to see what it looks like.

**Comment by NathanKell** [comment] 2015-07-22 01:47
@jrossignol There _is_ a weird bug that some users are encountering, however: they get exceptions that Kerbin World-First etc isn't a valid agent. The fix seems to be to revert to a clean Squad folder, although I have no idea why that helps since it's not like they'd have changed anything there.

**Comment by NathanKell** [comment] 2015-07-22 02:03
Update: Disregard. Seems to be linked to ATM compressing the agent's png.

**Comment by jrossignol** [comment] 2015-07-22 02:09
Yup...  I've seen that so many times that I don't even investigate.  In fact, I'm probably going to put a check for that issue in Contract Configurator to make people aware of it (rather than having them report it on the thread).

The other time it happens is when doing a blind DDS4KSP convertion on all assets.  And the ATM compression generally shouldn't be a problem - unless the user has bat ATM configs that don't ignore `*/Agencies/*` *or* a mod that doesn't use the standard paths.

**Comment by NathanKell** [comment] 2015-07-22 02:13
@Kibbick just reported removing ATM didn't fix it, which seems odd.. :\

Yeah, DDS4KSP is even more dangerous...

**Comment by jrossignol** [comment] 2015-07-22 02:15
Have a look at his log file - a recent version of Lack's Stock Extension also has this problem, and I'm sure there could be others.

**Comment by NathanKell** [comment] 2015-07-22 02:17
Had a problem with killing that agent? Wow.
Yes, RP-0 requires SXT, so that seems a good place to check. Thanks!

**Comment by batuhantasli** [comment] 2015-07-22 02:17
I'm on 64 bit linux build so I don't use ATM but I still get that error. If I make a clean install it works though as NathanKell said.

**Comment by NathanKell** [comment] 2015-07-22 02:21
Conveniently I'm a collab on the repo so I can fix it if the error's still in the repo. ^_^

**Comment by NathanKell** [comment] 2015-07-22 02:35
@jrossignol thanks for that tip, would never have though to check SXT of all place. Fixed by https://github.com/Signatum/SXT/commit/1db779fac9b9ad43d5fc6e1354ca365ea2593dde

**Comment by jrossignol** [comment] 2015-07-22 02:40
Funny, because I'd only mentioned it because the user who reported it just reported back that Lack confirmed it as a bug (although looks like you beat him to the revert).

**Comment by jrossignol** [comment] 2015-07-22 02:42
Actually, I should throw this out there - it can remain in DDS *if* you add a scaled logo (1/4 size) in PNG.  That's why the failure happens - KSP tries to downscale directly from the texture memory, which doesn't work for DDS.  If there's already a downscaled version, KSP skips that step.

**Comment by NathanKell** [comment] 2015-07-22 02:43
Oooh, interesting. Thanks for that!

**Comment by NathanKell** [comment] 2015-07-22 02:44
Uh, that's because DDS only loads as readonly whereas PNG I think defaults to not loading as readonly.

**Comment by jrossignol** [comment] 2015-07-22 02:44
Bingo.  And it can happen with ATM because ATM will load PNGs as readonly too (for lower memory consumption, I believe).

**Comment by NathanKell** [comment] 2015-07-22 02:46
Yep! Unless they're marked as leave-as-readable which ATM _should_ do these days but perhaps not.

**Comment by NathanKell** [comment] 2015-07-22 02:58
@jrossignol if you're still up, the one other issue I'm having is that Sounding Rocket contracts don't seem to generate once there are a lot of other contracts available. However, there are only 33 total contracts loaded, and only 5 in the menu, and the SR contracts are their own group. Anything I can do there? The requirements are met and there are no exceptions in the log.
I can set CC info to DEBUG if that's liable to help.

**Comment by jrossignol** [comment] 2015-07-22 03:25
I'd recommend CC to DEBUG for anyone doing contract modding (it only adds a little bit more to the logs than what in INFO).

There's a lot of code in there to try to enforce fairness in the contract generation.  Each group is given equal preference and within that group they are chosen using a weighted selection.  Looking at your weights in those three contracts (10/13/20), they are all within a ratio of 2.0 - so I'm not too concerned.  I should mention that the weighted selection happens before the requirement checks (as the requirements checks can potentially be heavy).  But it also tries to generate at least one contract in the group before moving on - so hypothetically it would make an attempt for each of the three types before trying to generate some other type of contract.

The other thing that can be a real killer is prestige.  You have them all set to Trivial, and KSP generates contracts into the three prestige groups based on the player's reputation.  At game start it's very common to not see any 3-star contracts at all (and 5 trivial ones sounds about right).  Also note with increased prestige you'll see fewer trivial contracts - with maxed prestige it's only one or two.

I really need to add that the last week or I feel like I've gotten an increased number of people reporting that they weren't seeing CC contracts showing up - but they've all been terrible reports with no information, so I can't really tell if it's just a blip in the background noise, or if there's an issue in the contract generation logic (I haven't touched it recently, so I suspect it's not broken).

All up:
* Try to clear all contracts with the F12 debug menu a half-dozen times to make sure that the RNG doesn't just hate you.
* Check prestige level
* Check there isn't something else with high weight in the group

And if you end up in the same spot after all that... report back and I'll do some more digging.

**Comment by NathanKell** [comment] 2015-07-22 03:43
Thanks for this!
Hmm. Would you suggest setting the high to prestige significant then, even though at base it really is a trivial contract? That makes me worry that I will have to set _all_ midgame or later contracts to be significant or more or they just won't be picked.

In my case, the issue was that I had forgotten I had a "collect science from space near Earth" contract accepted and alive. Once I completed that, the SR contracts went back to being generated. That would fit in with the prestige thing above, since that's also a trivial contract and KSP may have only allowed a single trivial contract _alive_ at that point. Then, with that slot cleared, both available trivial contracts were generated by you, so _you're_ in the clear :)

**Comment by jrossignol** [comment] 2015-07-22 03:55
Yeah, the KSP contract system definitely has some things to be careful of.  When doing a contract pack I tend to try to:
 1. Have contracts across all prestige levels.
 1. Have contracts that work for multiple prestige levels, but morph a bit (something like station in LEO = Trivial, station in Moon orbit = Significant).
 1. Avoid early-game Exceptional contracts

I also aim for maybe a 50/30/20 split - but that's just a mental guideline I go for - I honestly don't know where my contract packs really sit.  Also, contracts packs are a bit of a different story than the full progression of RP-0.

Anyway, in your case, you could either bump up this sounding record contract (I agree it should be trivial though), or bump up some of the other ones to reduce crowding.  Or, put sounding rockets together with other stuff in the same group, and use weights to get the distribution you want to see.

Another option to consider - GameData/Squad/Contract/Contracts.cfg has AverageAvailableContracts set to 10.  For RP-0 you could definitely make an argument for using a MM config to increase that.

**Comment by NathanKell** [comment] 2015-07-22 04:00
Followup to this: I had forgotten that all the record contracts are prestige trivial. So there were four more trivial contracts in play than I thought there were.

I removed prestige from them.

**Comment by jrossignol** [comment] 2015-07-22 04:01
Careful there!   Removing prestige means they are available for any prestige level - which isn't what you really want in that case.

Also - autoAccept contracts are exempt from the limits - so you don't need to worry about those.

**Comment by NathanKell** [comment] 2015-07-22 04:03
Well, they're record contracts and autoaccept so while they are exempt, maybe the fact that they had a prestige level lowered the slots for other trivial contracts?

**Comment by jrossignol** [comment] 2015-07-22 04:06
A generated contract will always have a prestige level - omitting it in the CONTRACT_TYPE is the same as listing all three.

And you're right...  they are exempt from the # of active contracts limit...  but I'm not actually sure if they are exempt from the # of slots limits....

**Comment by NathanKell** [comment] 2015-07-22 04:06
Ah, we crossed paths, I didn't see your post https://github.com/KSP-RO/RP-0/issues/166#issuecomment-123557207
Yeah, I'll definitely want to increase that, since there are a lot of concurrent milestone contracts but we also want to leave room for the repeatables.

To clarify the above: the sounding rocket contracts have not had their prestige changed (they are all trivial). However, I noticed the record contracts also were all trivial prestige, and they shouldn't have a prestige at all, they're autoaccept record contracts.

**Comment by NathanKell** [comment] 2015-07-22 04:06
Ah, I see

**Comment by jrossignol** [comment] 2015-07-22 04:10
Confirmed - I was wrong.  For the number of slots, autoAccept contracts ARE counted.  So if you have all 4 of your record contracts up, that's going to mess you up in trying to get the others.

You can consider changing one or two sets to Significant, and I think this makes a big case for globally increasing the contract limit via MM for RP-0.

**Comment by NathanKell** [comment] 2015-07-22 04:11
I think I'd rather go with the latter solution, since other than really late crewed records they're all trivial.

**Comment by NathanKell** [comment] 2015-07-22 04:15
And done. Thanks again!

**Comment by jrossignol** [comment] 2015-07-22 04:16
No problem!

Okay, back to FPS drop.  I've done some testing and haven't been able to reproduce.  Can you try removing all but the record contracts from the game entirely and letting me know if the FPS drop still occurs?  Also, check for any log spam while the FPS drop is occurring.

**Comment by NathanKell** [comment] 2015-07-22 04:27
Alas (or perhaps happily) I don't experience any FPS drop, so I can't test that. :]
I did check @Shurikeeen 's log for spam and there wasn't any, but it had soooo many mods loaded, so that's why I suggested trying to repro clean.

**Comment by Shurikeeen** [comment] 2015-07-22 10:18
Removing Wider Contracts App fixed it. Very strange.

**Comment by Shurikeeen** [comment] 2015-07-22 10:20
That also give a huge boost to the overall FPS.

**Comment by jrossignol** [comment] 2015-07-22 14:39
I've had that report a few times, but have never been able to reproduce.  I've gone through the code (all 150 lines of it) with a fine tooth comb and was able to figure out how to get rid of a couple GetComponentInChildren calls (expensive unity calls).  Hopefully that should improve it - give [Wider Contracts App 1.1.3](https://github.com/jrossignol/WiderContractsApp/releases/tag/1.1.3) a try.

**Comment by Shurikeeen** [comment] 2015-07-22 15:30
@jrossignol Still getting a FPS drop with that.

**Comment by jrossignol** [comment] 2015-07-22 15:38
Same or better?  One last attempt, dev dll [here](https://github.com/jrossignol/WiderContractsApp/blob/master/GameData/WiderContractsApp/WiderContractsApp.dll?raw=true).  If that doesn't do it, then I can't offer anything else - the problem is somewhere in the stock code, and it's all getting rewritten in 1.1, so I don't want to invest a ton of time into it.

**Comment by Shurikeeen** [comment] 2015-07-22 15:44
It was the same 20 FPS on the pad with 1 part.

**Comment by NathanKell** [comment] 2015-07-28 00:10
Closed as it appears to not be an RP-0 issue in the end...

**Closed by NathanKell** 2015-07-28 00:10 UTC
