### ISSUE TITLE
RP-0 developmental - Cannot train for new mission

### ISSUE THREAD

**Issue by NoMrBond** [KSP-RO/RP-0#787] opened 2017-11-16 22:56 UTC
Basic rundown of training issue I'm experiencing with RP-1dev (latest all+dependencies)

1. Train astronaut for a capsule (X-1)
2. Train for a mission (X-1)
3. Run and complete mission
4. R&R/Recovery break
5. Cannot mission train again for the same capsule

---

Have two pilots which have both flown a single X-1 mission and cannot be flown again.  They can be sent to refresher courses, but not mission courses which is preventing them from flying again.

Their profile lists the capsule proficiency and mission proficiency (expired).

---

[Edit] After approx 10x the R&R period (~120 days?) they could be entered into the 'X-1:" Mission" courses again, so now I'm not sure if this is a bug?  Will attempt to measure this downtime period more precisely.

**Comment by GrKl30** [comment] 2017-12-28 19:07
I noticed the same bug (?) twice. Once in a previous career, one in my current one. In my current carreer, my astronaut that had this problem has retired since, so I could not check if the 10x R&R period 'solution' works. In any case, this is certainly something to look at before the 'final' release of RP-1

**Comment by GrKl30** [comment] 2018-01-09 10:02
Follow up on this bug, I have no deep knowledge on how these logics where implemented, but diggin through the code a bit and re-reading 'NoMrBond' edited comment, it would seem to me that the variable "trainingMissionExpirationDays " in 
https://github.com/KSP-RO/RP-0/blob/Developmental/Source/Crew/CrewHandlerSettings.cs
(line 29) could be the cause. Exactly 120days just as he ('NoMrBond') supposed to be the additional delay. By the name of this variable, it would seem that this should only be used for Training mission expiration. 

My feeling is that, for each mission the Kerbal pilot should be trained. But after the mission is ended, the Kerbal is enable to be trained for another mission in the same pod type, as he's expired mission time was not yet reached. So he can not be re-trained, and must wait the previous mission training expiracy date to be able to be re-trained to enable him to fly a new rocket with the same pod type.

If I am correct, it seems the solution is either:
- to allow Pilots to fly new rockets as long as they still have an un-expired mission for that pod (thus not be re-trained for each rocket/mission)
- to force end the mission expiracy date to 'now' for the pod when the craft is recovered in the function "VesselRecoveryRequested" in
https://github.com/KSP-RO/RP-0/blob/Developmental/Source/Crew/CrewHandler.cs

**Comment by NathanKell** [comment] 2018-01-13 21:27
Yep, it's supposed to clear training flags when a mission completes. So I must have a bug where that's not happening.

**Comment by NathanKell** [comment] 2018-01-14 00:01
Ok, that will hopefully do it. That forces all mission training to expire during a crew member's recovery.

**Comment by NathanKell** [comment] 2018-01-25 04:33
Given feedback that it's resolved, closing this. Please poke if reencountered.

**Closed by NathanKell** 2018-01-25 04:33 UTC
