### ISSUE TITLE
B9 Procedural Wings and KSP 1.3.1

### ISSUE THREAD

**Issue by draqsko** [KSP-RO/RP-0#1093] opened 2019-05-21 10:45 UTC
Not really an issue with RO/RP-1 but I figured I'd pop up a warning since others could fall into the same trap.

Apparently B9 Procedural Wings - Fork v 0.91 and v 0.90 are not really compatible with KSP 1.3.1 and RO/RP-1, yet CKAN will show them as compatible. Installing either of those versions will not work as experienced by myself and reported by other users here: https://forum.kerbalspaceprogram.com/index.php?/topic/175197-13x14x15x16x17x-b9-procedural-wings-fork-go-big-or-go-home-update-40-larger-wings/&do=findComment&comment=3590506

and here: https://forum.kerbalspaceprogram.com/index.php?/topic/175197-13x14x15x16x17x-b9-procedural-wings-fork-go-big-or-go-home-update-40-larger-wings/&do=findComment&comment=3591683

I see exactly what the first post sees, all existing craft have their wings borked and reverted to the default size and shape, and the hotkey ('J') does not work for resizing them. And like the second post, reverting to 0.40.13 also fixes the problem for me as well.

The forum OP for RO has the right version linked so I'd recommend funneling people on 1.3.1 to use that version in the RP-1 Install guide rather than the one CKAN suggests. Don't know if this problem exists in 1.6.1.

**Comment by siimav** [comment] 2019-11-21 12:44
Closing this as the issue isn't relevant in 1.6+ any longer

**Closed by siimav** 2019-11-21 12:44 UTC
