### ISSUE TITLE
Geostationary Weather Satellite

### ISSUE THREAD

**Issue by ctiberious** [KSP-RO/RP-0#741] opened 2017-08-01 23:18 UTC
I don't see this talked about anywhere else.

I had this happen to be on my first run of this contract but I thought it was maybe something I'd done wrong so I hacked my savegame to resolve the problem.  Now I've taken a second "Geostationary Weather Satellite" contract and I'm experiencing the same issue.  Normally when I launch Geostationary satellites, I start by putting the satellite into a low parking orbit (around 220km circular orbit).  Then at AN or DN, I'll put apoapsis out to 35786km.  Finally, at apoapsis, I circlize and correct inclination during the same burn.  In my current launch, I've just completed the parking orbit.  The target area I need to put my satellite over to complete the mission (Location: Geostationary Weather Satellite) is on the other side of the planet and since I have only launch less than 10 minutes ago, I have not even flown over it yet.  But already the "Testing connectivity of instruments to ground stations" has already started to count down.

Because of the way I did my previous launch, it took me more than 6 hours to finish getting into the proper orbit.  The result was the "Testing connectivity...." line said it was complete, the obit said it was complete, but the "Location" line still needed to be done, even though my satellite was basically directly over the target location.  I'm guessing the problem has something to do with the timer starting too soon but I'm not familiar enough with how the contract is setup to know for sure.

**Comment by baldk** [comment] 2017-08-10 20:59
I am experiencing the same problem. It never acknowledges that I am right over the location tag.

Geostationary Weather Satellite contracts are currently not an option for me, which is a shame. So if some could fix it that would be nice.

**Comment by sgrif** [comment] 2018-03-07 15:16
Can confirm that it's never detecting that you're close enough to the waypoint. I thought it might just be super finicky, but this should *definitely* be close enough.
![20180307081343_1](https://user-images.githubusercontent.com/1529387/37100302-d2501da2-21df-11e8-8aa2-fb65446bbd21.jpg)

**Comment by pap1723** [comment] 2018-03-07 15:43
This has to be a Contract Configurator issue as I know the contract is
written correctly. I will look into this more.

**Comment by glilienthal** [comment] 2018-03-08 22:17
I can  confirm the problem.

**Comment by pap1723** [comment] 2019-01-18 03:18
Anyone shown if this is still an issue?

**Comment by lpgagnon** [comment] 2019-01-18 03:21
I haven't tried in current career, but in previous (Novemberish), I experienced the opposite, waypoint being considered visited when I had never gotten near it. Seems likely to be a different manifestation of the same problem, waypoint proximity not working right.

**Comment by siimav** [comment] 2019-03-08 11:01
@pap1723 has figured out what the issue is and made some changes to the CC code to fix it. I have tested the modified CC dll and the location checks appeared to be working perfectly with it.

**Comment by pap1723** [comment] 2020-01-08 15:46
This will be an outstanding bug, but it will still be there until CC fixes it from their end.

**Comment by siimav** [comment] 2020-10-09 11:29
CC fix has been released and the contract is confirmed to be working correctly now.

**Closed by siimav** 2020-10-09 11:29 UTC
