### ISSUE TITLE
Tracking Issues with new contracts

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#670] opened 2017-06-01 17:20 UTC
I'm creating this Issue to track any feedback people have with the new contracts for 1.2 that @pap1723 was nice enough to create for us.

Whether it is a spelling or grammar mistake, a description and goal that don't match (like, text says you must get to 140km but it triggers at 100km), a contract that appears broken or has a bad trigger, etc, please mention it here. Please describe the issue you have in as much detail as possible, and ideally link to the Contract you're discussing, or call it by its One True Name.
https://github.com/KSP-RO/RP-0/tree/master/GameData/RP-0/Contracts

@pap1723 feel free to edit this Issue to your liking, or direct people who mentions issues here.

**Comment by Sander815** [comment] 2017-06-02 16:10
I would like to help with testing this, but are these contracts already in the master branch? Because the latest change in that link seems to date from 2 months ago.

**Comment by pap1723** [comment] 2017-06-02 16:23
The contracts are in the Pap-Contracts branch, which as of yesterday, is up
to date with the master branch for all other commits than the contracts.

So in other words, use the Pap-Contracts branch and thanks for testing!

**Comment by Sander815** [comment] 2017-06-04 20:49
In the first_Orbitrecover contract the "reach 6500m/s" is checked on launch. The contract completes with a tiny hop on the launch pad.

**Comment by glilienthal** [comment] 2017-06-05 22:19
In general the new contracts seem to generate a lot less money than the old ones. Is that on purpose? Is that a good balance? Considering that the F-1 research costs almost as much as the whole moon landing brings. (Or did that change? )

**Comment by glilienthal** [comment] 2017-06-05 22:19
I love that we have now a mars landing contract, and sample returns, and, and, and! I'll test this the next time rl doesn't interfere with KSP.

**Comment by pap1723** [comment] 2017-06-05 22:24
@glilienthal for things like the Moon Landings, I used almost the exact same values as before. What you have to remember is the values inside the contract CFG files are not necessarily what you receive upon completion.

I have classed many missions as Exceptional prestige. These pay 1.5x the listed value in the CFG. Also, missions to the Moon pay 3.5x the listed values in the CFG. So, if a CFG file shows the payout for an Exceptional mission to the Moon to be 100,000, it is actually 100,000 x 1.5 x 2.5 = 525,000.

**Comment by pap1723** [comment] 2017-06-05 22:25
@Sander815 where did you launch from?

**Comment by pap1723** [comment] 2017-06-05 22:27
@NathanKell I hardly modified that first_OrbitRecover contract. Do you know why it is setup to just require orbital velocity to be reached instead of a true orbit?

**Comment by NathanKell** [comment] 2017-06-05 22:36
@pap1723 because you might be going 7.5km/sec with a 140km apogee (i.e. never even go suborbital, by KSP terms, since 140km is the atmo interface) and that should be fine. In general, any suborbital (in real, not KSP terms) flight over 6.5km/sec should broadly man-rate the heat shield (c.f. Big Joe).

**Comment by pap1723** [comment] 2017-06-05 22:39
That makes sense. I will change the contract to require traveling at least
6500 km on at least a suborbital trajectory. Should fix the error that was
reported.

**Comment by NathanKell** [comment] 2017-06-05 23:11
[Here is Big Joe for reference](https://en.wikipedia.org/wiki/Big_Joe_1). Trajectory: 153km apogee, 2292km downrange, 6657m/s max velocity (I presume ECI not ECEF, so rather lower ECEF). [See Also](https://www.nasa.gov/mission_pages/mercury/missions/BJ-1.html).

**Comment by Sander815** [comment] 2017-06-06 17:05
Another strange bug:
I just did the first_MoonFlybyUncrewed contract  and the contract completed at 5000km above the moon, without sending any science. Can someone maybe try to replicate this? Because combined with the previous bug I'm starting to think there might be a problem on my end.

**Comment by NathanKell** [comment] 2017-06-06 17:08
Was not able to confirm last night. Contact did not complete without
science.

**Comment by leudaimon** [comment] 2017-06-06 17:27
The same as Nathankell. Completed the contract twice, both times needed to transmit science before completion. Relevant info (and intended in the contract), you can complete it even if you transmit science from the Moon's SOI before reaching 5000km.

**Comment by Sander815** [comment] 2017-06-06 17:37
Yes, I just noticed that too. The contract works fine, I just send the science first, then reached 5000km, and the contract completed. I just thought It was meant you had to transmit science from below 5000km. 

Did anyone else try doing a small hop on the first_Orbitrecover contract?

**Comment by glilienthal** [comment] 2017-06-06 20:55
RE: amount of payouts: Yes, makes total sense. The amounts are the same. I believe you, and I looked at them.

**Comment by rsparkyc** [comment] 2017-06-07 16:10
For the sun-synchronous satellite, we don't actually enforce that we're in a synchronous orbit. Wikipedia has a good table for orbital period, altitude, and number of orbits per day: https://en.wikipedia.org/wiki/Sun-synchronous_orbit
Should we implement some or logic in the contract to align with one of the items in that table?

**Comment by NathanKell** [comment] 2017-06-09 07:39
For first solar powered satellite, is it as intended that a new vessel is
not required?

**Comment by pap1723** [comment] 2017-06-10 03:58
Thanks for the updates!
I have fixed the Solar Powered Contract to require a NewVessel and I have modified the Lunar Orbiter contract slightly to not fire early.

**Comment by NathanKell** [comment] 2017-06-10 07:24
Orbit Recovery contract: the orbit/speed states lack disableOnStateChange = true which means that as soon as you leave the state they uncomplete, or at least they did for me just now (last ~10 minutes of the Soviet stream on twitch I just did). I suggest trying with disableOnStateChange = true like the First Crewed Orbit contract.

This may not be your bug, of course, it might date back to me. :)

**Comment by pap1723** [comment] 2017-06-10 13:53
You are using the older version of that contract (I uploaded a new one yesterday), but even in the new one, I forgot to have the disableOnStateChange = true value set. Fixed now!

Also made the margin of error smaller in the initial First GEO contract.

**Comment by NathanKell** [comment] 2017-06-10 20:12
Ah, gotcha! And sorry, thought I'd done a pull.

**Closed** 2017-06-17 20:48 UTC
Labels: balance, in progress
