### ISSUE TITLE
Crewed records HasCrew is sticky

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1722] opened 2022-07-15 22:06 UTC
Crewed records can get completed by visiting an uncrewed vessl that satisfies the altitude/speed target right after a crewed vessl that doesn't.

Example: place satellite in orbit; put crewed plane on runway, recover it right away. Go to satellite via tracking station. As soon as satellite is loaded, the next crewed Altitude and Speed records (if less than satellite's state) immediately complete.

Looking in the .sfs right after recovering plane, one can see the next crewed records' HasCrew PARAM has state=Complete, presumably preserved from while the plane was on the runway. 

Don't know if CC bug or misconfigured contract. .cfg just has type=hascrew, mincrew=1; .sfs shows a possibly-fishy `disableOnStateChange = False`

**Comment by NathanKell** [comment] 2022-07-16 02:13
From what I understand this is a CC bug.

`disableOnStateChange = False` is correct -- if it were true then the parameter, once it went true, would never go to false again.

**Comment by pap1723** [comment] 2022-07-16 02:16
I think this goes back to some conversations that we ran into when we had the docking and Space Stations contracts written a little differently. What would be great is if a specific craft was "attached" to a specific contract. For example, before a launch, the player would say, this craft is for "x,y,z" contract and CC would read that parameter and then only allow that craft to complete that contract (until the player "removed" the link due to failure).

I don't know how big of a rabbit hole that gets into though.

**Comment by NathanKell** [comment] 2022-07-16 02:34
I don't think that's really related? The issue is that CC is reading some of a vessel's state (alt, speed) without reading the *rest* of the vessel's state (crewcount)

**Comment by pap1723** [comment] 2022-07-16 02:39
Ah, looking at how the contract is designed, I bet if we wrap the HasCrew inside of the ReachState it would work properly.

**CURRENT CONTRACT**
PARAMETER
	{
		name = ReachState
		type = ReachState

		minAltitude = @/crewedTargetAltitude
	}
	PARAMETER
	{
		name = HasCrew
		type = HasCrew
		minCrew = 1
	}

**PROPOSED FIX**
PARAMTER
{
	name = ReachState
	type = ReachState
	
	minAltitude = @/crewedTargetAltitude

	PARAMETER
	{
		name = HasCrew
		type = HasCrew
		minCrew = 1
	}
}

**Comment by NathanKell** [comment] 2022-07-16 03:36
Oooh, good call! It's weird that the param isn't reset on load of vessel, but that should probably fix it?

**Comment by pap1723** [comment] 2022-07-16 03:40
That is likely because it is not wrapped in a VesselParameterGroup, but I don't know how well that works with the structure of these types of contracts.

**Comment by NathanKell** [comment] 2022-07-16 04:55
I think I made them before I understood VPGs, maybe?

**Comment by NathanKell** [comment] 2022-07-16 04:56
Yep. https://github.com/KSP-RO/RP-0/commit/8fe582e36ee3c208330eb1113b4750a310433d21

**Comment by siimav** [comment] 2022-09-18 17:51
Anyone willing to test the change that Pap suggested?

**Comment by Test-Account-KSP** [comment] 2022-10-14 12:18
The fix does not work. I changed CrewedAltRecord.cfg as described above, launched a plane, switched to a satellite using kerbalism tab in flight, and several altitude records got completed.

**Comment by siimav** [comment] 2022-10-14 12:24
A thing to keep in mind is that contract cfg changes only apply after the contract gets regenerated. So if you had it accepted before making the changes then the test wasn't valid.

**Comment by Test-Account-KSP** [comment] 2022-10-14 12:31
But it's a record, not a contract... does it mean I need to start a new game for the changes to have effect?

**Comment by siimav** [comment] 2022-10-14 12:31
Probably easiest to complete the current record level which would then cause the next level to get generated and autoaccepted.

**Comment by Test-Account-KSP** [comment] 2022-10-14 12:34
Ok, I see only crewed altitude record 160km in my list of active contracts. It means that 180km is not generated yet. But when I switched to the satellite, 180km, 200km and 500km got completed too - so they were generated, autoaccepted and then completed.

**Comment by Teykn** [comment] 2022-11-24 09:24
I think a single VPG should work. Something like this should work.
```
PARAMETER
{ 
    name = crewAlt
    type = VesselParameterGroup
    title = Reach an altitude of @/crewedTargetAltitude

    PARAMETER
    {
        name = HasCrew
        type = HasCrew
        minCrew = 1
    }
    PARAMETER
    {
        name = ReachState
        type = ReachState
        minAltitude = @/crewedTargetAltitude
    }
}
```

Could also add `completeInSequence = true` to the `ReachState` parameter, but I don't think it's necessary. Would need someone to test it though.

**Comment by lpgagnon** [comment] 2022-12-08 00:54
... or maybe not. I just got a blast of crew altitude records proc out of the blue when simming a probe in orbit - even though I hadn't done any crewed flights since my last probe in orbit

**Comment by siimav** [comment] 2023-02-09 12:30
The fix has been released.

**Closed by siimav** 2023-02-09 12:30 UTC
Labels: help wanted
