### ISSUE TITLE
Later American placement, ctiberious

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#417] opened 2015-12-17 18:54 UTC
@ctiberious 

You can post questions or notes on your progress here if you like. It might also be good to post a statement of your intended goal :)

**Comment by ctiberious** [comment] 2015-12-17 19:12
I am going to be working up a timeline for the American Atlas, Thor/Delta, and Titan rockets.  Basically from inception to their modern versions.  I plan on including the more well know (to me at least) 2nd/3rd stages for these rockets as well (i.e., Able, Agena, Centaur, Transtage, etc).  I know a lot of the earlier versions of these rockets have already been correctly placed, but I'd like to work on getting the later and modern era versions placed correctly.  Once I have the initial time line created, I'll see about getting it posted here for comments.  After that, I'll work on actually moving engines, configs and tanks into the correct nodes.

**Comment by ctiberious** [comment] 2015-12-17 23:48
Still working up the timeline but should have something available tonight or tomorrow.  In the mean time I've come across a couple things.  Much of this is just notes I wanted to stick up here but some are questions I hope someone might be able to comment about.

1) We don't really have the GRC X-242 SRM that was used on the Vanguard.  Closest option we have is the Altair which isn't available until a later tech node.
2) We've got an MB-3-3 engine which is just the other designation for the LR-79-13 that was used on early Thor/Delta rockets.  That's cool but the MB-3-3 part we have has a few issues.  For one, it's too large to fit on the 2.44m dia Thor tank.  It also doesn't look like it's got the right thrust or ISP.  And finally, it doesn't have any other configurations.  Since the RS-27 and RS-27A are basically just upgrades of the MB-3-3, I'd think we should include those configurations.
3) Looks like I didn't realize there was a non-FASA version of the LR-105 and LR-89 atlas engines.  I think those need to have the configs updated like the FASA versions have.
4) There appears to be two sets of engines on the LR91 series Titan engine.  One set has configurations and a single ignition available.  The other had 5 ignitions and an "Engine" button but when you press it, nothing comes up.  I'm not sure what this second engine is for but it seems to sometimes interfere with the configurable engine.
5) The transtage we currently have has 490L of available volume remaining by default.  Was there multiple versions of this stage?
6) We have an "AJ10 (Early)" that has the -37, -42, -142 and -118D configs.  And we have an "AJ10 (Mid)" that has the -104D and 118E configs.  Based on what I'm finding, the -37, -42, -142 and -104D should probably all be part of the Early version and all the -118 configs should probably be part of the Mid part.
7) We don't have the AJ10-118 which was used on the early Delta A.  Might not be a big deal since there is very little difference between it and the -118D config (used on Delta B and later) which we do have.
8) We don't currently have the configs for the -118F and -118K used on Delta 1 and 2.  I have a separate PR that would add these two configs to the AJ10 (Mid) part we already have but there is some question as to whether those configs should be on their own part.  Maybe I just need to generate a "AJ10 (Late)" part?
9) We don't have a Castor 4 SRM.  I could submit a PR that would add that part but I'll have to base it off an existing part because I can't draw.  :)
10) From what I can tell, FASA doesn't have parts of the RD-180 (Atlas III & V), RS-68 (Delta IV), Aerojet 60A (Atlas V) or Aerojet 73F (Atlas V) .  Nor do we have a tank specifically for the DCSS-4 or DCSS-5.  I know there are some other parts mods that have at least some of these parts and since they are used on the rockets I'm working on, I'm going to include them in the timeline.

**Comment by ctiberious** [comment] 2015-12-18 02:55
So here is a simple excel spreadsheet with the timeline that I have so far: https://www.dropbox.com/s/bpyzmy6hg097fqi/Timeline.xlsx?dl=0

The first page (Timeline) is a breakdown of parts by year.  Most of the data I'm using is coming from b14643.de.  I should point out that I'm not saying these are the years when the parts actually became available.  They are just the years where the parts seemed to have been first put into use on the rockets I'm looking at.

The second page (Nodes) shows the nodes I'm proposing the parts and configurations be moved to.  I've taken some liberties here to try and improve flow a bit.  For instance, the Atlas MA-5.1 and MA-5.2 engines were both basically available at the same time (SLV-3A in 1968, SLV-3C in 1967) but I'm proposing that the MA-5.1 engines be introduced with Heavy Orbital Rocketry while the MA-5.2 wouldn't show up until Refined Rocketry.  Mostly I'm suggesting this (in this particular example) because the MA-5.2 was used on both the SLV-3C (1967) and SLV-3D (1973).  Since there was effectively no difference between the two (at least no game mechanic differences) I decided to split the difference between the two and suggest releasing the SLV-3C tank and MA-5.2 engines in the 1970 era.
Another example is the Titan IV tanks and engines which first flew in 1989 but which I'm suggesting not turn up until the 1990 era (Exotic Alloys/Experimental Rocketry).
I have tried to keep Hydrolox engines/configs in the Hydrolox nodes, other engines in the Rocketry nodes, SRM/SRB in the Solid nodes and tanks/decouplers in Construction nodes.  Though I am only guessing that Advanced Metalworks and subsequent nodes are more advanced Construction nodes since they all lead directly from Advanced Construction.

**Comment by stratochief66** [comment] 2015-12-18 03:29
Looks like solid work so far.

On the 'Nodes' page, can you colour code the parts/configs, to show which once are already placed as you suggest, which ones would be moved earlier than they are placed now, which ones later, and which ones are currently not placed at all (so these would be your suggested 'first placement' positions)?

The first placement ones are probably those of the most immediate interest to us.

@NathanKell your feedback/comments on the suggested placements would be appreciated.

**Comment by ctiberious** [comment] 2015-12-18 17:23
I'll work on that now.

Here's a question.  What are the Staged Combustion tech nodes meant to represent?  Should we have upper stage, non-hydrolox engines located in these nodes?  For instance, the Titan LR91?

**Comment by stratochief66** [comment] 2015-12-18 17:45
It actually refers to the fuel cycle used by the engine. The first American engine to use it was the RS-25, I think.

https://en.wikipedia.org/wiki/Staged_combustion_cycle

**Comment by ctiberious** [comment] 2015-12-18 22:28
As requested, I've updated the Timeline spreadsheet so that the Nodes page is color coded.
Red indicates that a part hasn't been placed and may not actually exist.
Yellow indicates that the part is in the correct node.
Blue indicates that I'm proposing having the part appear in an earlier node.
Green indicates that I'm proposing having the part appear in a later node.
Orange indicates that the part isn't currently in the "correct" type of node, though it may be in the correct era.  See below for explanations of those.

I've also included, in parenthesis, the actual part name(s) of existing parts.  Mostly this is so I can more easily locate the parts when I get ready to put together the PR for all these changes, but it also shows which parts/configs don't yet exist.

Most of the changes would be to FASA parts though there would ultimately also be changes to parts in ATK, Squad, SXT, Vens, Cryoengines and Soviet Engines.

Orange explanations:
The Agena D and Centaur D tanks are currently in the correct era but I believe that since they are fuel tanks they should be in the appropriate construction node.
The LR-79-9 and AJ-10-142 are both in the correct era but currently in a construction node.  I'm guessing this was to separate them from other engine configs that also become available in this era, but not sure if that separation is really needed since each configuration has it's own initial cost.
The Bell 8081 and 8247 are both in non-engine nodes and, I believe, in the wrong eras.  Again, they may be in non-engine nodes to keep them separate from Bell configs that become available at the same time but not sure that is really necessary.
The RD-180 is the only engine I've looked at that isn't in a Hydrolox or "standard" engine node.  I also think it's in the wrong era, but it's possible that it should be in "Modern Staged Combustion" instead of "Modern Rocketry" as proposed on the spreadsheet.

I think we need to add a X-242 SRM that was used as the third stage of the Vanguard.  I know it is eventually (and rather quickly, all things considered) replaced with the Altair but it's a missing piece for the Vanguard.  If you agree, I can create a part based on the Altair model.
The AJ10-104D is currently the default config for the SXTAJ10Mid.  But the -104D was only ever used on the old Able-Star so I'm thinking it should be moved over to the SXTAJ10 part since that includes all the Able configurations.  Though the Able-Star was a bigger stage so that might explain why it's on the Mid version.
The AJ10-142 and AJ10-118D are currently the last two avaiable configs for the SXTAJ10 but since they are the first Delta 2nd stage engines (Thor-Delta and Delta A-D), I'm thinking they should be on the Mid part.
There is currently no AJ10-101A config.  It was used on the upgraded Able stage so I think it should be added to the early AJ10 part.  The difference between it, the AJ10-42 (Able 1) and AJ10-104D (AbleStar) are small, but with those early rockets, even small improvements can have big effects.
There is currently no AJ10-118 config.  It was only ever used on the Delta A but I think it should be added for thoroughness.
We definitely need the AJ10-118F and AJ10-118K.  I've got a PR already proposed which would add those configs to the existing SXTAJ10Mid part but if we really want a separate part for them (since they do use different fuel from their predecessors) I can setup a new SXTAJ10Adv.
We don't currently have an RL-10B-2-1 config which is the RL10B config used on the DCSS matched with the Delta IV.  I believe that even though there isn't a huge difference between it and the RL-10B-2, we should still include this configuration.
We don't currently have a Castor 4 which I think we need to include.  I can create a part based on the Castor 4A that does exist.
I think we should add the GEM-60 (for Delta IV) and Aerojet 60A & 73F (for Atlas V) though I've got no idea what model would be best suited for those.  I suppose I could create the GEM-60 using the GEM-46 we have, and just make it larger.  But no idea how to deal with the two Aerojet SRMs.
We need the SRB used on the Titan IVB but I need to find more about them.  b14643.de lists their specs but they only call them "ATK" which I'm guessing is not actually the name of the motors.  And astronuatix just lists them as "USRM" or "Upgraded Solid Rocket Motors.
As much as I'd love to see models for the DCSS and Atlas II, III and V (not to mention the various Thor-Delta and Delta tanks), those can just as easily be created using procedural tanks.  But if there is a mod out there that works with RO that already has those tanks, I've indicated which nodes I think they should appear in.
The MB-3-3 part (FASADeltaMB3LFE) needs to be properly sized and needs the RS27 and RS27A configurations added to it so it can be used as an alternate model for Delta rockets.

One final thing to note.  I've placed the parts for the Atlas II, Delta III, Delta IV and Titan IV all in the 1990 era because they all technically showed up at about the same time.  However, Titan IV really only came about because of the Challenger accident.  Before then, the Titan series was going to be retired in favor of using the shuttle so development on it was stopped.  If the shuttle had never been a factor, it's quite possible that the Titan IV could have come about sooner so I could see moving it's parts into the 1980 era.  I know that isn't completely accurate but it could improve the flow of these three rockets a bit.

**Comment by NathanKell** [comment] 2015-12-18 22:58
1. For the GRC X-242: My policy thus far has been that one can pretty much recreate it with a 1x + 3x set of Baby Sergeants, and thus didn't feel the need to try to make a stock part serve as such. I believe we will have such a part when Raidernick finishes his Vanguard LV set. While I agree that a part modeling that should exist in one or more of the part packs for RO/RP-0, I don't think it's necessary for "minimal" (i.e. sans additional part packs like FASA/RN/KW/etc) RP-0 play.
2. The tankbuttly MB-3-3 from FASA should get the same configs as the stock LR-79 (though perhaps not the H-1 configs since FASA does have an H-1 model), @SirKeplan is working on making that sort of thing easier. As to sizing, I believe it was sized such that the nozzle would be the right size, and hang the tankbutt. It might, however, be worth just removing the part and replacing it with a cloned FASA LR89, since that at least lacks a tankbutt (though it also lacks any plumbing).
3. See above re: @SirKeplan extracting configs so they only need be updated in one central location.
4. What parts are used for those two engines? I am aware of (in FASA) there being two LR91 models we use--one represents only the LR91-AJ-3, used on the 8ft Titan I upper, whereas the other represents the LR91-AJ-5 and above, used on the 10ft Titan II/III/IV upper. That is needed because of FASA tankbutts.
5. I do not believe there was; it's probably that the volume was configured one way, and then the utilization value on something changed (EC probably) but volume was never changed. Bug.
6. No, the distinction is based on the nozzle. Short-nozzle AJ10s use the first model, AJ10s with nozzle extensions use AJ10Mid. The 104D used on Ablestar used a nozzle extension (see the Isp shift), and that nozzle extension (and, indeed, entire stage design) was civilianized as AJ10-118E / Delta E some years later.
7. We do indeed lack a 118, which according to at least b14643 has a notably lower Isp than 142 used on Thor-Delta (or 118B used on Delta B-D).
8. Discussed on the other PR.
9. I thought we did have a Castor 4 in one part pack or another. But you are right--we only have 4A and 4AXL, no 4.
10. FASA only covers pre-1970 NASA/USAF kit. RD-180 is Russian and very post-1970. BobCat's Soviet Engines has an excellent model, as do various Atlas V mods. The best RS-68 is BahamutoD's. We do have [an AJ-60A](https://github.com/KSP-RO/RealismOverhaul/blob/d3509c468ae89ced4436e458c40be4ee2fb9904d/GameData/RealismOverhaul/RO_SuggestedMods/KWRocketry/RO_KWRocketry_Solids.cfg#L1341). Could have sworn we had an AJ-73F as well (@A1Ch1 you have any idea?) but can't find it at the moment. Certainly we have the GEMs in KW.

**Comment by A1Ch1** [comment] 2015-12-18 23:16
Yes, we had the AJ-73F in KW but it was renamed the AJ-60A. Aerojet never really gave the Atlas 5 boosters an official designation until recently, there were various names floating around including AJ-73F and AJ-62, but their recent marketing material refers to the motor as the AJ-60A.

**Comment by NathanKell** [comment] 2015-12-18 23:27
Next, responding to [this comment](https://github.com/KSP-RO/RP-0/issues/417#issuecomment-165911510):

Some general notes: the hydrolox nodes are for both engines and tanks; that is why hydrolox tanks belong there. Some engine upgrades are placed in construction nodes because the construction nodes, as their descriptions state, represent advances in materials science. So one might unlock an engine in a given rocketry node, then research better materials science which allows a higher chamber pressure and thus unlocks an engine upgrade. You're right that there's a gameplay basis for this as well (separation of configs). Consider the RD-103 and the RD-103M: if we were only to use rocketry nodes to unlock configs, then both configs would have to unlock in the same node, making the RD-103 (instead of the 103M) nearly pointless. Instead, the RD-103 unlocks in Early Rocketry, and the RD-103M config (but not engine) unlocks in Early Construction. This means one can pay a bit of science to get the basic engine, or more science to get the engine and an unlock. It's the science cost, and the fact that one could simply skip the earlier config and jump straight to the later config, which makes putting more than one config in any given tech node less than optimal.

What eras should the 8081 and 8247 be in? The 8081 (used on Agena B) was flown quite early on, AFAIK, so it makes sense to place it between the TL1 and TL2 rocketry nodes. The 8247 was a many-ignitions derivative of the 8096 and flown in the late-TL2 era, and it was placed in Flight Control due to its connection with Gemini and the avionics requirements of many reignitions.

The RD-180 is in a staged node because it's a staged combustion engine; only gas generator (open cycle) and pressure-fed engines of non-hydrolox propellant mixtures go in the regular rocketry nodes. Hydrolox goes in hydrolox, and staged combustion / closed cycle engines (except hydrolox ones) go in the staged combustion nodes. Regarding its node, it was placed in TL6 (90s/early 2000s) as it was a derivative of the TL5 RD-170/171 designed for Atlas V use.

I discussed the X-242 and the AJ10 placement in the prior comment. I agree that it's worth adding the AJ10-101A, with TestFlight it will have a difference in reliability compared to the -37, since otherwise the -37 is strictly better.

I would say it is worth making an Adv version of the AJ10, since ideally we'd ask @signatum to make a 188F/K when he has time (same process as the AJ10Mid). They were visually distinct, I believe--certainly the K is!

Concur on RL10B-2-1.

Atlas and Delta SRMs discussed above.

I thought we did have a USRM part (it was an advanced, non-segmented replacement for the UA1207 AFAIK). But looks like we don't.

MB-3-3 discussed above.

Regarding TLs for Atlas II/III/V and Delta II/III/IV: I would suggest TL5 for Atlas and Delta II, TL6 for III and III, and TL7 for V and IV. For Titan, I would place it as TL5, since as you say it was effectively Shuttle-era tech. IVB would be TL6.

**Comment by A1Ch1** [comment] 2015-12-18 23:35
The USRM is alternately known as the SRMU and is in the KW pack.

**Comment by NathanKell** [comment] 2015-12-18 23:35
Ah. Right. Thanks!

**Comment by SirKeplan** [comment] 2015-12-19 02:10
Ahh yes , one of the things i see when extracting configs, the LR79/RS27/H-1 etc. seem to be a bit of a muddle, with FASA and squad engines having different subsets of the configs to apply to each part. so that's one of the things that has to be decided and cleaned up a bit.

**Comment by NathanKell** [comment] 2015-12-19 05:55
@SirKeplan: I guess given this refactor we'll have to give up having H-1 on the same part as LR79. Another clone \o/

**Comment by ctiberious** [comment] 2015-12-19 23:58
2. For the MB-3-3, the part definitely seems to be large.  If I take a procedural tank, set it to 2.44m diameter, then attach the MB-3-3, the top of the engine is larger then the tank.  Most of the pictures of Thor-Delta and early Delta rockets I'm looking at appear to tapper down to the engine.  I can post a picture of what I'm seeing.  Maybe it's just a quirk with my install?  Assuming not, if I shrink it's diameter a bit, then add the RS27 and RS27A configs to it, I think it would be a good model, especially since it does have the plumbing.
3. Having consolidated configs sure would be great.  But in the mean time, I don't have an issue updating the configs.  The two parts that need it are based on Squad models so I'm guessing its for people to recreate the Atlas without FASA.
4. You misunderstand.  There's a single part (FASAGeminiLR91) but that part has two ModuleEngines*, two ModuleGimbal and two ModuleEngineConfigs.  It looks like the engine is suppose to have vernier included for roll control.  The trouble is when you right click the part, the menu gives you two buttons for Gimbal and two buttons for Engine.  If you click on the Engine button for the actual engine, you've fine.  You'll get the select the engine config you want to use.  But if you click on the Engine button for the vernier, then later try to open the Engine button for the engine, you no longer get to select an engine config.  I'm not sure what is causing that to happen.
6. Oh, that makes sense.
7. I'll include a config for the 1188 on the first AJ10 model since presumably it will have the same size nozzle as the 118D.
9. Admittedly, I don't use every available part pack.  Seems like KW has some of the parts so I'll add that to my game but if it doesn't have the Castor 4, is there a problem if I simply clone (with correct thrust and ISP of course) the 4A?
10.  I see.  b14643.de lists an AJ72F on the Atlas V 400 and the AJ60A on the Atlas V 500 but looking at the numbers, they appear to be the same engine.  And since KW has the AJ60A already, just need to make sure it's placed correctly.

Hydrolox tanks: Hmm.  Ok.  Only hydrolox tank I noted that is in the Hydrolox node is the Centaur.  Saturn SIVB and SII are in construction nodes.  And when I placed the Centaur D2, D3, D5 and T, I put them into construction nodes and no one commented.  I just figured construction was for tank, and the engine nodes were for engines.  If you think the hydrolox tanks should be in the hydrolox nodes, I can put them there in the appropriate era.  Just say the word.

Configs in construction node: Ok.  That makes sense.  I wasn't thinking about advances in material science being represented by the construction nodes (yes, I should read those descriptions more).

Agena engines: Like I said, this was preliminary.  I've since found some other first flight data.  Looks like the Bell 8048 first flew in 1959 followed quicly by the Bell 8081 in 1960.  It looks like the Bell 8096 and Bell 8247 both had first flights as early as 1963.  I can't find any specific dates for the 8096-39 but it seems that version of the Agena was only launch on Titan 3 so it should show up in an appropriate era for that rocket.  Based on Nathan's comments about why some engine configs show up in non-engine nodes, 8081 and 8247 are likely already in good nodes.

RD180: Ok.  I'm not up to speed on the differences between open cycle and closed cycle engines so I'll defer to the experts there.  :)  

Delta II/III/IV: The Delta II didn't start service until 1989 or 1990 which is why I put it's engine and boosters in TL6.  The GEM-46 boosters used on the Delta II-H first flew in 1998 which would put them near the end of TL6 but without creating a new TL6.5 Solids node, I figured they were better off being placed in the TL7 solids node.
The Delta III rocket was a Delta II-H core (RS27A engines with GEM-46 boosters) topped with the newly developed DCSS.  It first flew in 1998, only had three launches, and only one of those launches was successful.  I'm proposing putting the RL10B-2 (used on the DCSS) into the TL7 Hydrolox node which means the Delta III and IV both basically become available at the same time.  But considering how quickly the Delta III was actually replaced, that's not a bad thing.
I suppose, alternatively, we could move the RL10B-2 and GEM-46 into appropriate TL6 nodes.  That would have the Delta II and III show up at effectively the same time.  Gameplay wise you'd likely get the Delta II first (research the 

Atlas II/III/V: Atlas II first flew in 1991 so it should definitely be a TL6 rocket.
Altas III first flew in 2000 so it should be a TL7 rocket.
Atlas V first flew in 2002 so it should also be a TL7 rocket.  I'm not really sure why the Atlas III was so quickly replaced by the Atlas V.  Bacially the V has a larger diameter so maybe engineers realized that the RD-180 engines were more then the "smaller" Atlas III needed.  At any rate, it really seems like the III and V should both be usable at about the same time.

LR79/H1: Since you mentioned that FASA has a model for the H-1, and we know it has a model for the MB-3-3 here's a suggestion.  Right now the MB-3-3 has only that one config.  I can update it so that it includes the MB-3-1, MB-3-2, MB-3-3, RS27 and RS27A configs.  Probably rename it to just "MB3".  Thus if you're using FASA, that's the engine you'd use for Delta with the H1 engine for Saturn.  But use the single Squad model for both the LR29/RS27/H1 configs.  That keeps us from having clones that aren't needed.

I've updated the spreadsheet mentioned in my ealier post with discussed changes.

**Comment by A1Ch1** [comment] 2015-12-20 01:09
Re: b14643 and AJ-73/60, I'd try to avoid relying too heavily on [b14643 for nomenclature](http://forum.nasaspaceflight.com/index.php?topic=32983.msg1335761#msg1335761)(or [using figures](http://forum.nasaspaceflight.com/index.php?topic=26915.msg812940#msg812940) [found there](http://forum.nasaspaceflight.com/index.php?topic=28357.msg883079#msg883079) without corroboration elsewhere). For instance, there are two references to RL10B-2-1 found by Google - one is Brugge's site and the other is to a [ULA presentation from 2009](http://www.ulalaunch.com/uploads/docs/Published_Papers/Upper_Stages/UpperStageEvolutionJPC2009.pdf) that indicates that the RL10B-2-1 is nominally an undeveloped evolution to the RL10B-2. Nowhere else uses the terminology RL10B-2-1 to distinguish between the 111 kN 465.5 s version on the Delta IV and the 110 kN 462 s version on the Delta III.

**Comment by A1Ch1** [comment] 2015-12-20 01:16
Re: Atlas III/V, the Atlas III was a technology demonstrator/risk mitigation project for the EELV Atlas V. Since EELV was intended as an evolution of current launch vehicle technology, both LM and Boeing used their "III" versions to pave the way for the evolution to the EELV, Boeing with the Delta Cryogenic Second Stage on the Delta III and LM with the RD-180 on the Atlas III. So it makes sense for the Atlas III and Atlas V tech to be available at the same time.

**Comment by SirKeplan** [comment] 2015-12-20 02:33
see https://github.com/KSP-RO/RealismOverhaul/pull/778 for what I’ve done so far. i split the LR79 into a new engine. once i'm done, it should be a lot easier to edit or place/price various engine variants. it will however force more consistency between part packs.

**Comment by NathanKell** [comment] 2015-12-20 04:30
1. RO sizes engines based on their nozzles, not their tankbutts. If the *nozzle* of that engine is scaled to be too large (it should be right about 1.2m for the LR79 / RS-27) then the scaling *should indeed* be changed, but we should not scale based on tankbutts at the cost of having wrong-sized nozzles.
2. Ok, cool. :)
3. Ah, sorry. Gotcha. Yeah, sounds like something is broken in the vernier configs (yes, the Titans other than II GLV had verniers).
4. Cool.
5. Yep, sounds good.
6. KW is definitely the pack to have for modern US solids. Yep, a clone of the 4A would serve well as the 4.

Re: Hydrolox. Ah, hmm. It may make sense to put later stuff in construction nodes then; I just know for the TL2 stuff (i.e. first Centaur D) it needs to be there since the tank won't work (the ability to store LH2 unlocks in that hydrolox node, not a construction node). Once that's unlocked, then tanks can be wherever.

On TLs, I'd tend to see TL7 as present tech, i.e. mid-2000s or later, leaving the early 2000s for TL6. Otherwise we get the oddity of the Atlas III in the same node as Vulcan.
I believe that was indeed more or less the case with Atlas III vs Atlas V: the III used the RD-180 but kept the tooling (though not the construction techniques) of earlier Atlases, whereas the V took full advantage of the RD-180's power (and the power of strapon boosters for early high-TWR kicks).

Regarding the LR79 and H-1 and RS-27: To the best of my knowledge, RS-27 *is* an H-1; they are the designation of leftover Saturn IB H-1s flown on Deltas (the performance implies they were slightly derated). RS-27A is just an H-1 with a 12:1 nozzle rather than 8:1, since Delta II has that long-burning core and most of the liftoff thrust comes from the strapons. Given how poor the FASA MB-3-3 model is (it's just a resized Agena Engine model, itself about of the quality of the FASA LR87/91 parts and very tankbutty, i.e. far below frizzank's later work) I'd sooner just see it hidden entirely.

**Comment by ctiberious** [comment] 2015-12-20 18:01
For TLs, Vulcan, Constellation and SLS don't even exist yet (I think there was one or two test flights of Aries 1 before Constellation was cancelled).  They shouldn't be placed in TLs with rockets that have been around for a decade.  Therefore I stand by my suggestion to put Atlas III & V in TL7.  But I also think we need to add a TL8 (Present tech: Late 2000's to mid 2010's) and TL9 (New Tech: Mid 2010's and beyond).  That way we can properly place existing rockets but still have some place to put the rockets we know are on the drawing boards.

MB3: Forgive my lack of knowledge here but what exactly is the "nozzle" on the models we use?  If I take a procedural tank and fit the MB3 to it, I have to make the procedural tank 4.3m diameter to match the diameter of the butt plate.  If I then add another procedural tank below the engine, I have to set it to 2.9m diameter to match the diameter of the engine bell.  I can't directly attach anything to the base of the engine bell, but just eyeballing it, it looks like it's about 1.8m diameter.  If we resize it so that butt plate is 2.44m, we'd end up with the engine bell being around 1.65m and the base of the bell being just over 1m.  The model has certainly got a very large butt plate, and as you mentioned it wasn't frizzank's best work, but resized I think it would be a nice looking engine for Thor/Delta.  But if you'd prefer just using the LR89 model, we can do that instead.  I've always just used the Squad version of the LR79 engine but that's mainly because there wasn't a good alternative in FASA.

**Comment by SirKeplan** [comment] 2015-12-20 18:53
If you think in terms of the engines, then Atlas III is definitely TL6, RD180 is essentially a cutdown RD170/171(a TL5 engine that flew in 1985), and was fully tested in 1997. the Atlas III tank was still using the same stainless steel monocoque "balloon" construction. the RL-10A-4-1 first flew on the Atlas III, but it was largely the same as the RL-10A-4(TL5). So in all i think most if not all Atlas III components should stay TL6
I do think adding a TL8 makes some sense for prospective parts on the drawing board, and tech about to be used now, as long as it is a noticeable technology upgrade.(the BE-4 perhaps)

I think the problem is you can't think of the TLs as fixed decades, they are progressions of technology that often manage to sync with real life decades.

so what we have right now is a bit like this i would say:
TL5 - 1980s tech
TL6 - 1990s early 2000s
TL7 - present day ish, 2005-2015 maybe
TL8? - mid 2010s onward

**Comment by NathanKell** [comment] 2015-12-20 22:42
TL5 starts in like 1977 and runs throuhg 1990 or so, but otherwise I'd say @SirKeplan has the right of the TLs.That would leave TL8 for anything new, though I would say that SLS is anything but new except for integration.

For nozzle, I do just mean bell--if in fact the exit of the bell is > 1.2m in diameter then we definitely need to scale it down, or just junk it and use the LR89 model (which I think both looks better, and gives us better flexibility).

**Comment by ctiberious** [comment] 2015-12-21 00:44
My problem is simply that if we assume TL6 is 90's - early 2000's, then Atlas II, III and V all become available at the same time.  That's not a huge issue for Atlas III which only flew a total of 6 times between 2000-2005 (2xIIIA, 4xIIIB).  But Atlas II flew for over a decade (63 total launches) and was only retired when Atlas V took over.  In game, the only things we really have to separate these three craft are the engines and configs.  If RD-180 wasn't fully tested and approved until 97, I say that's close enough to the next era to push it's release to TL7.  That gives a clear distinction between Atlas II and Atlas III/V.  Then with the inclusion of at least one (and I'd still say two would be better) additional tech level, we still have a place to put newer stuff.

As for the MB3, I'll rework it to use the LR89 model.

**Comment by SirKeplan** [comment] 2015-12-21 01:41
Atlas II, III and V all coming along at the same time is a little unfortunate i suppose, but in real life they did all come along in the space of only 11 years.

and The RD-180 is in a different node to LR89/LR105 engines anyway, so it's not like players will necessarily unlock them at exactly the same time.

**Comment by NathanKell** [comment] 2015-12-21 05:26
We need to make a distinction between the various parts that make up an LV, and the LV itself. While the Atlas V wasn't introduced until TL7 (I think we can agree it's TL7, especially if we reserve TL8 for Vulcan) and certainly the Atlas V CCB would be TL7, but the RD-180 engine used by it would be TL6.

**Comment by ctiberious** [comment] 2015-12-21 17:15
Ok.  Here's something that might resolve my concern with Atlas.  It's something I do in my game and hadn't considered including here but maybe we should.
An issue I always have with my Thor and Delta recreations is that, unlike Atlas and Titan, there are no tank parts so I have always used procedural tanks.  Using procedural tanks isn't a problem but it does mean that my Thor and Delta rockets require an extra part or two for their avionics.  In my game, the way I got around this was to add avionics to the Delta Cone Rocket Fuel Tank [FASADeltaConeLFT](top half of early Thor and Delta rockets), and to create a 2.44m avionics part (using the Saturn IU model).  What if we do that for Atlas III and V?  Create a 3.05m avionics part for Atlas III and a 3.81m avionics part for Atlas V?  Could even try to have these avionics parts include rcs for roll control (I believe Atlas III & V have hydrazine based roll control in the interstage to replace the verniers used on previous rockets).  That would resolve the problem of avionics while also allowing the engine to show up separately from when the rocket itself becomes available.
For Atlas II, I can take the existing Atlas H model and expand it to account for the extra height on Atlas II.

We can do the same thing for Delta.  We'd need a 2.44m avionics for Delta 0, I, II & III, and a 5m for Delta IV.  Only thing I'm not sure of is whether we should have multiple 2.44m avionics parts since Delta L-M and 0 need less avionics capacity than Delta II.  And just add avionics to the Delta Cone for earlier Thor and Delta.

**Comment by A1Ch1** [comment] 2015-12-21 17:49
It was the Atlas II that replaced the vernier system with a hydrazine RCS; the Atlas III and V used independent vectoring of the RD-180's thrust chambers for roll control. The other issue is that Atlas-Centaur vehicles and Delta past a certain point used integrated avionics in the second stage for the whole vehicle.

**Comment by ctiberious** [comment] 2015-12-21 18:15
For the Atlas, that would still work.  It would mean you couldn't really fly Altas V until the Centaur D5 becomes available.  Though it does mean we need to tweek the avionics on Centaur D3 and D5 since I think they are currently setup to only have avionics for themselves and the payload.  Not for the full Atlas III/V LV.

Delta is another matter since we don't have a model for DCSS but creating a separate avionics part for the DCSS-3, DCSS-4 and DCSS-5 would have the same effect.

Also, I guess ignore my comment about the FASADeltaConeLFT.  By the time I got around to updating it in my game, I wasn't really flying those older versions.  Just tried it in my game now to make sure I wasn't talking out my back side and noticed that the dimensions are wrong.  It tapers from around 1.26m to 2.5m which makes it either too large to fit with the 2.44m Thor tank, or too small to support the 1.45m delta upper stages.

**Comment by ctiberious** [comment] 2015-12-30 18:34
I'm just about ready to start setting up PRs for the changes we've been talking about.  Some of these changes, even though they are mostly tech node changes, need to be made on the Realism Overhaul github since most of the engine config techRequired settings are found there.

Only thing I'm still curious about is my suggestion for the Delta and DCSS avionics parts.

I'm also considering something with the FASADeltaConeLFT.  The early Thor (Thor-Able and Thor-Delta specifically) had very small upper stages.  I believe the Able and first generation of Delta 2nd stages were something like 0.8m diameter which means that the existing FASADeltaConeLFT would likely work with some adjustments.  I've never been able to find anything that specifies the complete Thor dimensions (specifically how narrow the top of the tank gets).  Does anyone see a problem with using the FASADeltaConeLFT for the top half of early Thor first stage tanks?

**Comment by Schnobs** [comment] 2016-01-05 01:51
Just a small tidbit: the 5-ignitions engine on the LR91 appears to be a vernier kind of thing, providing roll authority. It doesn't have different configurations, that's why nothing comes up; it's also listed first in the part stats so that at first glance, the LR91 appears to have 9kN.

IIRC someone somewhere once mentioned that it's actually the gas generator.

**Comment by ctiberious** [comment] 2016-01-06 23:27
Along with the above three PRs, I've also created RealismOverhaul PRs 800, 801, 802, 803, 804, & 805 to cover the changes talked about above.  I'm having a little issue with the tree.yml update but once I get that resolved, all the PRs for this issue should be in.

**Comment by NathanKell** [comment] 2016-01-18 06:23
Quick note: it was always my intention to add essentially unlimited-tonnage avionics units once the digital age really got going; TL6 or so. I believe that would solve the Delta II / Atlas II/III/V / etc. issues.

**Comment by SirKeplan** [comment] 2016-02-23 15:12
What happened about the RL10B-2? it seems like there should be two variants, the older with 462s isp as used on Delta III, and the newer one with 465.5 secs isp.

**Comment by ctiberious** [comment] 2016-02-24 16:51
@SirKeplan there was some question as to whether the RL10B-2 actually had two variants.  The two versions are only apparently mentioned on b14643.de site and there wasn't enough supporting evidence.  Between that lack of supporting evidence and the fact that there is less than a 1% difference between the two sets of values (0.67%), I stayed with just the one variant we already had.

**Comment by SirKeplan** [comment] 2016-02-24 16:54
@ctiberious Hmm ok, if we were to keep with one, i'd say we should make it the one with an ISP of 465.5, as that is definitely the correct value is it's stated in the current(2013) delta IV handbook, and the ULA and aerojet websites.

**Comment by ctiberious** [comment] 2016-02-24 16:55
@SirKeplan I'm fine with that.

**Comment by pap1723** [comment] 2018-12-02 01:30
Incredibly good information in here. Not relevant with the new tech tree.

**Closed by pap1723** 2018-12-02 01:30 UTC
